#!/usr/bin/env bash

process_name=$1

if [ -z "$process_name" ];
    then
        echo "usage:\n    ps-uptime <process_name>"
        exit 1
fi

ps -eo pid,comm,cmd,start,etime |grep -i $process_name
